
export default () => {
  const data = [
    {
      Num: 1,
      NDL: 56710,
      Annee: 2014,
      Nom: 'Xahu',
      Prenom: 'Stain',
      Type: 'fondateur',
      Genre: 'homme',
      Email: 'ABCD@gmail.com',
      Telephone: '0794662115',
      Website : 'momo.com',
      projectname : 'key',
      
      link: '/editLI',
    },
    {
        Num: 1,
        NDL: 56710,
        Annee: 2013,
        Nom: 'Xahu',
        Prenom: 'Stain',
        Type: 'fondateur',
        Genre: 'homme',
        Email: 'ABCD@gmail.com',
        Telephone: '0794662115',
        link: '/editLI',
      },
    {
      Num: 1,
      NDL: 56710,
      Annee: 2013,
      Nom: 'Xahu',
      Prenom: 'Stain',
      Type: 'fondateur',
      Genre: 'homme',
      Email: 'ABCD@gmail.com',
      Telephone: '0794662115',
      link: '/editLPI',
    },

    {
      Num: 1,
      NDL: 56710,
      Annee: 2013,
      Nom: 'Xahu',
      Prenom: 'Stain',
      Type: 'fondateur',
      Genre: 'homme',
      Email: 'ABCD@gmail.com',
      Telephone: '0794662115',
      link: '/editLS',
    },
    {
      Num: 1,
      NDL: 56710,
      Annee: 2013,
      Nom: 'Xahu',
      Prenom: 'Stain',
      Type: 'fondateur',
      Genre: 'homme',
      Email: 'ABCD@gmail.com',
      Telephone: '0794662115',
      link: '/editLS',
    },
    {
      Num: 1,
      NDL: 56710,
      Annee: 2013,
      Nom: 'Xahu',
      Prenom: 'Stain',
      Type: 'fondateur',
      Genre: 'homme',
      Email: 'ABCD@gmail.com',
      Telephone: '0794662115',
      link: '/editLS',
    },
    {
      Num: 1,
      NDL: 56710,
      Annee: 2013,
      Nom: 'Xahu',
      Prenom: 'Stain',
      Type: 'fondateur',
      Genre: 'homme',
      Email: 'ABCD@gmail.com',
      Telephone: '0794662115',
      link: '/editLS',
    },
  ];

  return data;
};
